// HtmlTemplate.jsx
import React from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
// import logo from "../../assets/logoName.png";
import "../../Styles/HtmlPdfStyles.css";

export default function HtmlTemplate({ markdownText }) {
  return (
    <div className="html-pdf-page">

      <img src="/images/logoName.png" className="html-watermark" />

      <div className="html-header">
        <img src="/images/logoName.png" className="html-header-logo" />
        <div>
          <h1 className="html-header-title">Smart AI Medical Report</h1>
          <p className="html-header-subtitle">Generated by Health Navigator</p>
        </div>
      </div>

      <div className="html-content-box markdown-body">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {markdownText}
        </ReactMarkdown>
      </div>

      <div className="html-footer">
        Health Navigator • AI Medical Assistance
      </div>
    </div>
  );
}
