import jsPDF from "jspdf";
import MarkdownIt from "markdown-it";

export async function generateReportPdf(markdownText, logoBase64) {
    const md = new MarkdownIt();
    const html = md.render(markdownText || "");

    const doc = new jsPDF({
        unit: "pt",
        format: "a4",
        orientation: "portrait",
    });

    // ---------------- HEADER ----------------
    try {
        if (logoBase64) {
            doc.addImage(logoBase64, "PNG", 40, 30, 150, 40);
        }
    } catch (e) {
        console.warn("Logo error:", e);
    }

    doc.setFontSize(20);
    doc.setTextColor("#0A4FA3");
    doc.text("Smart AI Medical Report", 40, 100);

    doc.setFontSize(12);
    doc.setTextColor("#555");
    doc.text("Generated by Health Navigator", 40, 120);

    // ---------------- WATERMARK ----------------
    try {
        if (logoBase64) {
            const gs = doc.GState({ opacity: 0.15 });
            doc.setGState(gs);
            doc.addImage(logoBase64, "PNG", 150, 300, 200, 60);
        }
    } catch (e) {
        console.warn("Watermark error:", e);
    }

    doc.setGState(new doc.GState({ opacity: 1 }));


    // ---------------- IMPROVED CONTENT (STYLING APPLIED) ----------------
    const contentContainer = document.createElement("div");
    contentContainer.innerHTML = html;

    // Global styling
    contentContainer.style.fontFamily = "Arial, sans-serif";
    contentContainer.style.fontSize = "12px";
    contentContainer.style.lineHeight = "1.5";
    contentContainer.style.textAlign = "justify";     // JUSTIFY ALL CONTENT
    contentContainer.style.width = "520px";

    // Style headings from markdown
    const h1List = contentContainer.querySelectorAll("h1, h2, h3");
    h1List.forEach(h => {
        h.style.fontSize = "14px";
        h.style.fontWeight = "bold";
        h.style.marginTop = "14px";
        h.style.marginBottom = "6px";
        h.style.textAlign = "left";   // headings should not be justified
    });

    // Paragraphs
    const pList = contentContainer.querySelectorAll("p");
    pList.forEach(p => {
        p.style.fontSize = "12px";
        p.style.marginBottom = "8px";
        p.style.textAlign = "justify";  // justified paragraphs
    });

    // Lists
    const listItems = contentContainer.querySelectorAll("ul li, ol li");
    listItems.forEach(li => {
        li.style.fontSize = "12px";
        li.style.lineHeight = "1.5";
        li.style.marginBottom = "4px";
    });

    // Bold
    const boldItems = contentContainer.querySelectorAll("strong, b");
    boldItems.forEach(b => {
        b.style.fontWeight = "bold";
    });


    // Render HTML into PDF
    await new Promise((resolve) => {
        doc.html(contentContainer, {
            x: 40,
            y: 150,
            width: 520,
            windowWidth: 800,
            autoPaging: "text",
            callback: () => resolve(),
        });
    });

    // ---------------- FOOTER ----------------
    doc.setFontSize(10);
    doc.setTextColor("#888888ff");
    doc.text("Health Navigator • AI Medical Assistance", 180, 820);

    return doc.output("blob");
}
