import fs from "fs";
import path from "path";

export function buildReportHtml(markdownHtml) {
  const logoPath = path.join(process.cwd(), "assets", "logo.png");
  const logoBase64 = fs.readFileSync(logoPath).toString("base64");

  return `
  <html>
  <head>
    <style>
      body {
        font-family: Helvetica, Arial, sans-serif;
        background: white;
        margin: 0;
        padding: 0;
      }

      .html-pdf-page {
        padding: 35px 45px;
        position: relative;
      }

      .html-watermark {
        position: absolute;
        top: 48%;
        left: 9%;
        width: 600px;
        opacity: 0.18;
        z-index: 0;
      }

      .html-header {
        display: flex;
        align-items: center;
        border-bottom: 2px solid #0A4FA3;
        padding-bottom: 12px;
        margin-bottom: 25px;
        position: relative;
        z-index: 2;
      }

      .html-header-logo {
        width: 220px;
        height: 60px;
        margin-right: 15px;
      }

      .html-header-title {
        font-size: 22px;
        font-weight: bold;
        margin: 0;
        color: #0A4FA3;
      }

      .html-header-subtitle {
        font-size: 12px;
        color: #555;
        margin: 2px 0 0;
      }

      .html-content-box {
        margin-top: 10px;
        padding: 10px;
        line-height: 1.5;
        font-size: 12px;
        text-align: justify;
      }

      .html-footer {
        text-align: center;
        margin-top: 40px;
        font-size: 10px;
        color: #888;
      }
    </style>
  </head>

  <body>
    <div class="html-pdf-page">

      <img src="data:image/png;base64,${logoBase64}"
        class="html-watermark" />

      <div class="html-header">
        <img src="data:image/png;base64,${logoBase64}"
          class="html-header-logo" />

        <div>
          <h1 class="html-header-title">Smart AI Medical Report</h1>
          <p class="html-header-subtitle">Generated by Health Navigator</p>
        </div>
      </div>

      <div class="html-content-box">
        ${markdownHtml}
      </div>

      <div class="html-footer">
        Health Navigator • AI Medical Assistance
      </div>

    </div>
  </body>
  </html>
  `;
}
